INSERT INTO TEMP SELECT * FROM TIME_TABLE WHERE TRAIN_KEY = :TR_ID1;
update TEMP set ID = NULL;
update TEMP set TRAIN_KEY = :TR_ID2;
update TEMP set HOURS = NULL;
update TEMP set MINUTS = NULL;
update TEMP set STOP = NULL;
INSERT INTO TIME_TABLE SELECT * FROM TEMP;